app:
  env: "dev"
  port: 8889
  app_name: "gin-scaffold"
  app_url: "http://localhost"
  start_time: "2023-03-25"
  machine_id: 1

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: 3306
  database: "go-demo"
  username: "root"
  password: "root"
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: "info"
  enable_file_log_writer: true
  log_filename: "sql.log"

log:
  level: "info"
  root_dir: "./storage/logs"
  filename: "app.log"
  format: "json"
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 30
  compress: true

jwt:
  secret: "secret"
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 10
  refresh_grace_period: 1800
  

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: "123456"
  pool_size: 100
  prefix: "gin_scaffold"